/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT MANUALLY
 * SEE buildSrc/util.js
*/

/** The number of glyphs along the width of the bitmap */
export const GLYPH_WIDTH: number = 16;

/** The number of glyphs along the height of the bitmap */
export const GLYPH_HEIGHT: number = 16;

/** The first index (inclusive) containing a valid glyph */
export const GLYPH_START: number = 65;

/** The last index (inclusive) containing a valid glyph */
export const GLYPH_END: number = 90;

/** A base64 data URL containing the bitmap */
export const GLYPH_DATA: string = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACAAQMAAAD58POIAAAABlBMVEX///////9VfPVsAAAAAXRSTlMAQObYZgAAAJZJREFUeNrt0KENAkEUhOFfPrkSOSVQwpNIShq58kpYSRlXCiUgnyThDkIgQSH3l19GDbPZz45y9VLZcl9ucBIYYWvE0iDl1ReVkaNtIHMVvjgkyLYejGS0QyQPsEZkwlpJbeCy+WpocSH60AYCB6KN874oHGepjb5DsAZCb5BRRT7BQQL9BaOWDAqPPv/4+GM2m83+2h36P3cB27HCKAAAAABJRU5ErkJggg==";
