name: Deploy Demo

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build-umd

    - name: Cull unused files
      run: |
        rm -f .gitignore .npmignore jest.config.js package.json package-lock.json README.md tsconfig.json tsconfig.test.json webpack.config.js 
        rm -rf types tests src node_modules buildSrc

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './'

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v2
